language: python
python: 3.3
env:
  - TOX_ENV=py33
#  - TOX_ENV=py34
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coverage combine
  - coveralls
