language: python
python: 3.4
env:
  - TOX_ENV=py34
  - TOX_ENV=docs
install:
  - pip install -r requirements/tests.txt
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coverage combine
  - coveralls
